# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-09 12:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gallery',
            options={'verbose_name_plural': '게시판'},
        ),
        migrations.AddField(
            model_name='image',
            name='thumbnail',
            field=models.BooleanField(default=True, verbose_name='썸네일 지정'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gallery',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Title'),
        ),
    ]
