# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-10 05:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20160609_2141'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorys',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='카테고리명')),
            ],
            options={
                'verbose_name_plural': '카테고리',
            },
        ),
        migrations.AlterModelOptions(
            name='image',
            options={'verbose_name_plural': '이미지'},
        ),
        migrations.AlterField(
            model_name='gallery',
            name='title',
            field=models.CharField(max_length=50, verbose_name='제목'),
        ),
        migrations.AddField(
            model_name='categorys',
            name='gallery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Gallery'),
        ),
    ]
