# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-10 05:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20160610_1415'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categorys',
            name='gallery',
        ),
        migrations.DeleteModel(
            name='Categorys',
        ),
    ]
