# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-10 05:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20160610_1438'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorys',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='카테고리명')),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Gallery')),
            ],
            options={
                'verbose_name_plural': '카테고리',
            },
        ),
    ]
