# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-11 16:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20160610_1455'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery',
            name='categorys',
        ),
        migrations.AddField(
            model_name='gallery',
            name='categorys',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='blog.Categorys', verbose_name='카테고리'),
            preserve_default=False,
        ),
    ]
