# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-15 02:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorys',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='카테고리명')),
            ],
            options={
                'verbose_name_plural': '카테고리',
            },
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='제목')),
                ('detail', models.TextField(verbose_name='내용')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('categorys', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Categorys', verbose_name='카테고리')),
            ],
            options={
                'verbose_name_plural': '게시판',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='images/', verbose_name='이미지')),
                ('thumbnail', models.BooleanField(verbose_name='썸네일 지정')),
                ('gallery', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='blog.Gallery')),
            ],
            options={
                'verbose_name_plural': '이미지',
            },
        ),
    ]
