# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-15 02:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_image_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='board_thumbnail',
            field=models.BooleanField(default=1, verbose_name='썸네일 지정'),
            preserve_default=False,
        ),
    ]
