# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-15 03:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_image_board_thumbnail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='board_thumbnail',
            new_name='thumbnail',
        ),
    ]
