# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-20 06:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20160620_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='categorys',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Categorys', verbose_name='카테고리'),
        ),
    ]
