# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-20 06:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20160620_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='thumbnail',
            field=models.BooleanField(default=0, verbose_name='썸네일 지정'),
        ),
    ]
